namespace APDiagnosticAndroid.Enums
{
    public enum SEEDKEYINDEXTYPE
    {
        //GREAVES_BOSCH_BS6_DEV,
        //GREAVES_BOSCH_BS6_PROD,
        GREAVES_ADVANTEK_BS6_A46,

        //ATUL_ADVANTEK_BS6_A46,
        //TVS_ADVANTEK_BS6_A46,
        SML_BOSCH_BS6_PROD = 1,
        SML_ADVANTEK_BS6_PROD = 2,
        SML_ADVANTEK_BS4_PROD = 3,
        KOEL_BOSCH_BS4 = 4,
        SML_ADVANTEK_BS6_A46,
      
        SEEDKEYALGO_VECV_BOSCH_BS6,
        SEEDKEYALGO_VECV_DELPHI_BS6,
        SEEDKEYALGO_VECV_AMT_BS6,
        SEEDKEYALGO_BOSCH_CV54,
        SEEDKEYALGO_VECV_DELPHI_TCIC,

        //GREAVES_BOSCH_BS6_DEV = 1,
        GREAVES_BOSCH_BS6_PROD = 2,
        //GREAVES_ADVANTEK_BS6_A46 = 3,
        ATUL_ADVANTEK_BS6_A46 = 4,
        TVS_ADVANTEK_BS6_A46 = 5,
        //SML_ADVANTEK_BS6_A46 = 6,
        GREAVES_SEDEMAC_BL_BS6 = 7,
        GREAVES_SEDEMAC_APP_BS6 = 8,
        GREAVES_SEDEMAC_BS6,
        BAJAJ_RIPEMD160_SECURITY = 1,
        BAJAJ_KEY1TO4_SECURITY = 2,
        BAJAJ_L3_SECURITY = 3,
        BAJAJ_L5_SECURITY = 4,
        BAJAJ_BALNET_SECURITY = 5,
    }

}
